### ISSUE TITLE
Create doesn't do anything

### ISSUE THREAD

**Issue by schlingel** [Meesayen/slush-gladius#1]
I've just setup slush-gladius but if I try to create a new project nothing happens after I entered the project data. (name, author, template engine, css engine, etc.) No file whatsoever is put in the current directory.

This is my setup:
Lubuntu 14.10

$> node -v
v0.10.25

$> npm -v
1.4.21

$> gulp -v
[11:29:50] CLI version 3.8.10

$> slush gladius -v
[slush] 1.0.1
[11:28:21] 3.8.10
[slush-gladius] 1.0.2

**Comment by Meesayen** [comment]
Thank you for the feedback. The problem was with a malformed package.json. v1.0.3 is working.
